### ISSUE TITLE
Detects https://github.com/thlorenz/deep-is/blob/master/package.json as missing

### ISSUE THREAD

**Issue by drazisil** [tophat/yarn-plugin-licenses#20] opened 2021-09-15 23:23 UTC
**Describe the bug**
States the the license for https://github.com/thlorenz/deep-is/blob/master/package.json is missing

**To reproduce**

1.add `deep-is@npm:0.1.3` as a dependency
2. run yarn license

**Expected behavior**
License is detected as MIT

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu 20.04, Mac OSX 10.14] Manjaro Linux  21.1.2
- Plugin Version: [e.g. 1.0]  master branch, https://github.com/tophat/yarn-plugin-licenses/commit/129a9267fa40fd0f3ab1ebc1a5da84af64a7f9b6 
- Node Version: [e.g. 12.16.1] v16.9.1

**Comment by noahnu** [comment] 2021-09-15 23:47
deep-is@0.1.3 uses an unsupported license format, see: https://github.com/thlorenz/deep-is/blob/f126057628423458636dec9df3d621843b9ac55e/package.json#L31.

Closing this as a duplicate of #15, we can continue the conversation there.

**Closed by noahnu** 2021-09-15 23:47 UTC

**Comment by noahnu** [comment] 2021-09-15 23:55
Should be fixed now.
